version: '3.7'

services:
  mysql:  
    image: mysql:5.7
    container_name: mysql
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD:"root"
      - MYSQL_DATABASE:"appdb"
      - MYSQL_USER:"user"
      - MYSQL_PASSWORD:"userpassword"
    restart: unless-stopped
    ports:
      - 127.0.0.1:13306:3306
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:

networks:
  default:
